import 'package:amti_fluttter_task1/utils/kml_makers.dart';

/// Utility class for creating orbit KML animations
class OrbitKml {
  /// Build an orbit KML animation around a location
  ///
  /// [content] is the orbit content generated by [tag] method
  static String buildOrbit(String content) {
    return '''<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2">
  <Document>
    <name>Orbit</name>
    <gx:Tour>
      <name>Orbit</name>
      <gx:Playlist>
        $content
      </gx:Playlist>
    </gx:Tour>
  </Document>
</kml>''';
  }

  /// Generate orbit content tag
  ///
  /// Creates a 360-degree orbit animation around the specified location
  static String tag(double latitude, double longitude, double zoom, double tilt, double bearing) {
    String content = '';
    
    // Create orbit with 36 steps (every 10 degrees)
    for (int i = 0; i <= 360; i += 10) {
      final lookAt = KMLMakers.orbitLookAtLinear(
        latitude,
        longitude,
        zoom,
        tilt,
        i.toDouble(),
      );
      content += '<gx:FlyTo>$lookAt</gx:FlyTo>\n';
    }
    
    return content;
  }
}
